### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by fleli723** [fleli723/sprint1#2]
- [x] **Sprint1 Backlog**
- [x] **Code Refactor**
- [x] Validate HTML & CSS
- [x] **Album search page**
- [x] Search form
- [x] Mock data
- [x] **Album search result page**
- [x] Populate data
- [x] Form validation
- [x] Data sanitization
- [x] Database query
- [x] Page layout (table)
- [x] Page layout if form invalid
- [x] **Survey info into database**
- [x] Form validation
- [x] Data sanitization
- [x] Database insert statement
- [x] Validate all pages
- [x] Remove the user input from the URL
- [x] **We Have HTML written after our closing  "<?php>"  tag**
- [x] Put comments on our methods to document the program 
- [x] Edit relative links
- [x] **Sprint review prep**
- [x] **Lets practice doing a Sprint review b4 hand**
- [x] **Add a third column in the albums table, that will include the exact duration of the album in seconds**
- [x] add topnavbar in seperate php file
- [x] style table result from album search
